### ISSUE TITLE
How to clear the cache from docker scout quickview

### ISSUE THREAD

**Issue by HuapingLiu** [docker/scout-action#13]
I have a big image, after running docker scout quickview, there is no space for my C disk. how to clear the cache from command docker scout quickview? Thanks.

**Comment by eunomie** [comment]
Hi,

There are two types of cache:
- one is where the image is copied to index it
- one is where we store the final SBOM file

The first is deleted after the image has been indexed. But if you experienced a failure during the index, it might still be there.
This cache is a `docker-scout` directory inside the temporary directory of the system. This temporary directory is defined as following on Windows:

> On Windows, it uses `GetTempPath`, returning the first non-empty value from `%TMP%`, `%TEMP%`, `%USERPROFILE%`, or the Windows directory

The second directory, where all the SBOMs are cached, is `%USERPROFILE%/.docker/scout/sbom`

Hope this helps.

**Comment by HuapingLiu** [comment]
Thanks a lot for the info. My issue was resolved.
