### ISSUE TITLE
Error: could not get the image ***/alphafold:pr-237

### ISSUE THREAD

**Issue by pozsa** [docker/scout-action#4]
Any ideas about what am I doing wrong here?
https://github.com/paulscherrerinstitute/alphafold-on-fire/actions/runs/5510604867/jobs/10045052401?pr=237

**Comment by pozsa** [comment]
I've tried that here: https://github.com/paulscherrerinstitute/alphafold-on-fire/actions/runs/5509254620/workflow, but got the same error: https://github.com/paulscherrerinstitute/alphafold-on-fire/actions/runs/5509254620/jobs/10041696438

This had no errors, but I had to comment out the 'image': https://github.com/paulscherrerinstitute/alphafold-on-fire/actions/runs/5509558117/workflow. It was capable of pulling the 'to' image from the registry though, so I think `docker/login-action` works for the auth part.

**Comment by sbe-arg** [comment]
I tried to use analyzing images from github registry locally today without luck. If you are also using github might be related.

**Comment by pozsa** [comment]
> I tried to use analyzing images from github registry locally today without luck. If you are also using github might be related.

Do you get the same error?

**Comment by cdupuis** [comment]
@pozsa, could it be that there is more than one tag passed into the `scout-action`? See the following screenshot where GitHub prints the parameters of the step:

<img width="951" alt="image" src="https://github.com/docker/scout-action/assets/206707/474fe205-6f74-4998-8e5b-7abbac356eb8">

**Comment by pozsa** [comment]
@cdupuis thanks for the tip
changing to `image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/alphafold:${{ steps.meta.outputs.version }}` solved the issue

**Comment by cdupuis** [comment]
@pozsa , thanks for the confirmation.
